version: "3.9"

services:
  nest:
    build:
      context: ./greenvast/Backend
      dockerfile: Dockerfile
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - PYTHON_SVC_URL=${PYTHON_SVC_URL}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/greenvast
      - REDIS_HOST=redis
    ports:
      - "4000:4000"
    depends_on:
      - python-ai
      - postgres
    volumes:
      - ./greenvast/Backend:/app

  python-ai:
    build:
      context: ./python-ai
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./python-ai:/app

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: greenvast
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
